#!/bin/bash

. ~/.sens
. ~/dotfiles/scripts/bash.sh
. ~/dotfiles/scripts/docker.sh
. ~/dotfiles/scripts/git.sh
. ~/dotfiles/scripts/npm-completion.sh
. ~/dotfiles/scripts/npm.sh
. ~/dotfiles/scripts/yarn.sh

killPort() {
	if [ -z "$1" ]; then
		echo "Usage: searchAndDestroy [numeric port identifier]" >&2
		return 1
	fi
	lsof -i TCP:$1 | awk '/LISTEN/{print $2}' | xargs kill -9
}

dnv() {
	nvm alias default $1
}

batchExec() {
	local args=""

	for arg in "$@"
	do
		args+=" $arg"
	done

	find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && pwd && $args" \;
}

export NVM_DIR=~/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

export PATH="./node_modules/.bin:$PATH"

export GITAWAREPROMPT=~/dotfiles/plugins/git-aware-prompt
source "${GITAWAREPROMPT}/main.sh"

[[ -s ~/dotfiles/plugins/z/z.sh ]] && source ~/dotfiles/plugins/z/z.sh

export PS1="\u@\h \W \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
