#!/bin/bash

. ~/.sens
. ~/dotfiles/symlinks/git

[[ -s ~/tools/z/z.sh ]] && source ~/tools/z/z.sh

md() {
	mkdir -p "$@" && cd "$@";
}

untar() {
	tar -zxvf $1
}

killPort() {
	if [ -z "$1" ]; then
		echo "Usage: searchAndDestroy [numeric port identifier]" >&2
		return 1
	fi
	lsof -i TCP:$1 | awk '/LISTEN/{print $2}' | xargs kill -9
}

dnv() {
	nvm alias default $1
}

alias ..="cd .."
alias nt="npm test"
alias wt="npm run watch-tests"
alias rw="npm run watch"
alias ns="npm start"
alias nl="npm run lint"

alias su="sublime ."

export NVM_DIR=~/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

export PATH="./node_modules/.bin:$PATH"
